name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        cache: pip
        cache-dependency-path: requirements/*.txt

    - run: pip install -r requirements/dev.txt

    - uses: pre-commit/action@v3.0.0
